config/routes.rb
LanguageNetwork::Application.routes.draw do
  get "home/index" => "home#index"

  resources :sessions, :only => [:new, :create]
  match "logout" => "sessions#destroy", :as => "logout"
  match "login" => "sessions#new", :as => "login"

  match "users/edit" => "users#edit", :as => "edit_profile"
  resources :users

  get "messages/inbox" => "messages#inbox", :as => "inbox"
  resources :messages

  root :to => "home#index"

end

app/models/comment.rb
# == Schema Information
#
# Table name: discussions
#
#  id         :integer          not null, primary key
#  content    :text
#  type       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  # hidden input for type in form
end

app/models/desired_language.rb
# == Schema Information
#
# Table name: languages
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  type       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class DesiredLanguage < Language
  has_and_belongs_to_many :users
  # attr_accessible :title, :body
end

app/models/known_language.rb
# == Schema Information
#
# Table name: languages
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  type       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class KnownLanguage < Language
  has_and_belongs_to_many :users
  # attr_accessible :title, :body
end

app/models/language.rb
# == Schema Information
#
# Table name: languages
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  type       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Language < ActiveRecord::Base

  attr_accessible :name
end

app/models/message.rb
# == Schema Information
#
# Table name: discussions
#
#  id         :integer          not null, primary key
#  content    :text
#  type       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Message < ActiveRecord::Base
  attr_accessible :sender_id, :receiver_id, :subject, :content, :unread

  belongs_to :sender, :class_name => "User"
  belongs_to :receiver, :class_name => "User"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  username            :string(255)
#  email               :string(255)
#  password_digest     :string(255)
#  gender              :string(255)
#  known_language_id   :integer
#  desired_language_id :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  has_and_belongs_to_many :known_languages
  has_and_belongs_to_many :desired_languages
  has_many :messages

  attr_accessible :email, :gender, :password, :password_confirmation, :username, :known_language_ids, :desired_language_ids, :address, :latitude, :longitude, :image, :about_me, :hobbies, :place_to_visit

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  validates :username, :uniqueness => true
  validates :email, :uniqueness => true

  mount_uploader :image, ImageUploader

  def received_messages
    Message.where(:receiver_id => self.id)
  end

  def sent_messages
    Message.where(:sender_id => self.id)
  end

  searchable do
    text :username, :email, :gender, :about_me, :hobbies, :place_to_visit
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_filter :require_login, :only => :new
  def index
    #@messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
    @message.update_attributes(:unread => false)

    @reply = Message.new
  end

  def new
    @user = User.find(params[:user_id])
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    @message.update_attributes(:unread => true)

    if @message.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
  end

  def inbox
    @current_user = User.find(session[:user_id])
    @messages = Message.where(receiver_id: @current_user.id)
  end

  def sent_messages

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:notice] = "Your email or password was incorrect."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "You have logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    if params[:location_search].present?
      @users = User.near(params[:location_search], 30, :order => :distance)
      # Finds users within 30 miles
      @users.select!{|x| x.known_languages.map(&:name).include?(params[:language_search])}
    #elsif params[:location_search].present? && params[:interest_search].present?

    # Doesn't fully work yet:
    elsif params[:interest_search].present?
      @interest_search = User.search do
        fulltext params[:interest_search]
      end
      @users = @interest_search.results
    else
      @users = User.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @users }
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @known_languages = KnownLanguage.all
    @desired_languages = DesiredLanguage.all

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /users/1/edit
  def edit
    # @user = User.find(params[:id])
    @user = current_user
    @known_languages = KnownLanguage.all
    @desired_languages = DesiredLanguage.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # def destroy
  #   @user = User.find(params[:id])
  #   @user.destroy

  #   respond_to do |format|
  #     format.html { redirect_to users_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<br>
<%#= image_tag "/images/babel_full.jpg" , :class => "front_image" %>
<div id="search">
  <h1 id="tagline">Find someone to babble with!</h1>
  <%= form_tag users_path, :method => :get do %>
    <p>
      <%= label_tag :location_search, "Where are you?" %>
      <%= text_field_tag :location_search, params[:location_search] %>
      <br>
      <%= label_tag :language_search, "Which language?" %>
      <%= text_field_tag :language_search, params[:language_search] %>
      <br>
      <%= label_tag :interest_search, "Which interests?" %>
      <%= text_field_tag :interest_search, params[:interest_search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  <%= link_to "View All Babblers", users_path %>
</div>

app/views/layouts/_nav.html.erb
<nav class="top-bar">
  <% if current_user %>
    <p>You are logged in as <%= current_user.username %></p>
    <%= link_to("Home", root_path) %>
    <%= link_to("Inbox", inbox_path) %>
    <%= link_to("Edit Profile", edit_profile_path) %>
    <%= link_to("Log Out", logout_path) %>

  <% else %>
    <%= link_to("Sign Up", new_user_path) %>
    <%= link_to("Log In", new_session_path) %>
    <%= link_to "Login (AJAX)", :login, :remote => true, :data => {"reveal-id" => "login_window"} %>
    <%= link_to "Register (AJAX)", new_user_path, :remote => true, :data => {"reveal-id" => "signup_window"} %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Babel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/nav' %>

<%= yield %>

<div id="signup_window" class="reveal-modal"></div>
<div id="login_window" class="reveal-modal"></div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
</body>
</html>

app/views/messages/_form.html.haml
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.hidden_field :sender_id, value: current_user.id
  .field
    = f.hidden_field :receiver_id, value: @user.id
  .field
    = f.label :subject
    %br
    = f.text_field :subject
  .field
    = f.label :content
    %br
    = f.text_area :content
  .actions
    = f.submit 'Send'

app/views/messages/_reply_form.html.haml
= form_for @reply do |f|
  - if @reply.errors.any?
    #error_explanation
      %h2= "#{pluralize(@reply.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @reply.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.hidden_field :sender_id, value: current_user.id
  .field
    = f.hidden_field :receiver_id, value: @message.sender.id
  .field
    = f.label :subject
    %br
    = f.text_field :subject
  .field
    = f.label :text
    %br
    = f.text_area :content
  .actions
    = f.submit 'Send'

app/views/messages/inbox.html.haml
%h1 Inbox

- @messages.each do |message|
  .inbox_row
    = image_tag message.sender.image, :class => "user_index_thumb"
    = message.sender.username
    = link_to message.subject, message
    %br

app/views/messages/index.html.haml
%h1 Messages#index
%p Find me in app/views/messages/index.html.haml

app/views/messages/new.html.haml
.message_box

  %h1 New Message

  = render 'form'

= link_to 'Back', users_path

app/views/messages/sent_messages.html.haml
%h1 Sent Messages

app/views/messages/show.html.haml
%h1
  = @message.sender.username
  says:
/ %p Find me in app/views/messages/show.html.haml
/ %p
/   From:
/   = @message.sender.username
.message_box
  %p= @message.content
  %p *****

  %p Send a reply?
  = render 'reply_form'

app/views/users/_edit_profile_form.html.haml
= form_for @user, :html_options => {:multipart => true} do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .first_row
    .edit_box
      .field
        = f.label :username
        %br
        = f.text_field :username
      .field
        = f.label :email
        %br
        = f.text_field :email
      / .field
      /   = f.label :password
      /   = f.password_field :password
      / .field
      /   = f.label :password_confirmation
      /   = f.password_field :password_confirmation
      .field
        = f.label :profile_picture
        %br
        = f.file_field :image
      .field
        = f.label :gender
        %br
        = f.label "Male"
        = f.radio_button :gender, "Male"
        = f.label "Female"
        = f.radio_button :gender, "Female"
      .field
        = f.label :address
        %br
        = f.text_field :address
    .edit_box
      .field
        = f.label :known_languages
        %br
        %div.scrollable_list
          - @known_languages.each do |language|
            %div.label_input_pair
              = check_box_tag "user[known_language_ids][]",language.id, @user.known_languages.include?(language)
              = f.label "#{language.name}"
    .edit_box
      .field.desired_languages
        = f.label :desired_languages
        %br
        %div.scrollable_list
          - @desired_languages.each do |language|
            %div.label_input_pair
            = check_box_tag "user[desired_language_ids][]",language.id, @user.desired_languages.include?(language)
            = f.label "#{language.name}"
            %br
  %br
  .text_box
    .field
      = f.label "about_me:"
      %br
      = f.text_area :about_me, :cols => 100
  .text_box
    .field
      = f.label "hobbies:"
      %br
      = f.text_area :about_me, :cols => 100
  .text_box
    .field
      = f.label "Somewhere awesome:"
      %br
      = f.text_area :place_to_visit, :cols => 100
  .actions
    = f.submit 'Update'

app/views/users/_new_user_form.html.haml
= form_for @user, :html_options => {:multipart => true}, :remote => true do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .sign_up_box
    .field
      = f.label :username
      = f.text_field :username
    .field
      = f.label :email
      = f.text_field :email
    .field
      = f.label :password
      = f.password_field :password
    .field
      = f.label :password_confirmation
      = f.password_field :password_confirmation
  .actions
    = f.submit 'Register'

app/views/users/create.js.erb
var top_bar = $(".top-bar");

$('#signup_window').foundation('reveal', 'close');

top_bar.empty().append("<%= j render 'layouts/nav' %>");

app/views/users/edit.html.haml
%h1 Edit Your Profile

= render 'edit_profile_form'

= link_to 'View Profile', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Who would you like to babble with?

- @users.each do |user|
  .user_box
    = link_to user.username, user
    %br
    = image_tag user.image, :class => "user_index_thumb"
    %br
    = user.address
    %br
    %br
    Let's Practice:
    - desired_languages = user.desired_languages.map { |language| language.name }
      -desired_languages.each do |language|
      %li= language

app/views/users/new.html.haml
%h1 Sign Up

= render 'new_user_form'

= link_to 'Back', users_path

app/views/users/new.js.erb
var signup_window = $("#signup_window");

signup_window.html("<%= j render 'form' %>");

app/views/users/show.html.haml
%br
= image_tag @user.image, :class => "profile_image"

.profile_text_box
  %p
    %b Username:
    = @user.username
  %p
    %b Email:
    = @user.email
  %p
    %b Gender:
    = @user.gender
  %p
    %b Known Languages:
    - known_languages = @user.known_languages.map { |language| language.name }
    %ul
      -known_languages.each do |language|
        %li= language
  %p
    %b Desired Languages:
    - desired_languages = @user.desired_languages.map { |language| language.name }
    %ul
      -desired_languages.each do |language|
        %li= language
  %p
    %b About Me:
    = @user.about_me
  %p
    %b Hobbies:
    = @user.hobbies
  %p
    %b Somewhere Awesome:
    = @user.place_to_visit


  = link_to 'Say Hi!', new_message_path(:user_id => @user.id)
  \|
  = link_to 'Back', users_path